version: "3.7"

services:
  maria:
    image: mariadb:10.4.7
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"
    environment:
      - MYSQL_DATABASE=bd_gdelt
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8110:3306
    volumes:
     - ~/gdelt-big-data/mariadb:/var/lib/mysql
